spring.application.name=kolesokz
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/kolesokz
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true